/* My Gramify — Assessment bank. Every question below is hand-written and
   tied directly to a specific chapter's content — no templates, no
   auto-generated combinations. */
window.QUESTIONS = {

nouns: [
  {"type":"mcq","prompt":"Which sentence uses a proper noun correctly?","options":["I visited paris last spring.","I visited Paris last spring.","I visited The Paris last spring.","I visited a Paris last spring."],"answer":1,"explain":"Paris is a proper noun — a specific, unique place — and is always capitalised."},
  {"type":"mcq","prompt":"Which noun is uncountable?","options":["chair","idea","furniture","book"],"answer":2,"explain":"Furniture is treated as a substance/whole, not counted individually — it has no plural form."},
  {"type":"mcq","prompt":"Which sentence correctly uses an uncountable noun?","options":["She gave me an advice.","She gave me some advice.","She gave me a advices.","She gave me some advices."],"answer":1,"explain":"Advice is uncountable: no a/an, and no plural -s."},
  {"type":"type","prompt":"Give the plural form of 'child'.","accepted":["children"],"explain":"Child has an irregular plural: children."},
  {"type":"type","prompt":"Give the plural form of 'mouse' (the animal).","accepted":["mice"],"explain":"Mouse has an irregular plural: mice."},
  {"type":"mcq","prompt":"Which shows correct possessive punctuation for one dog?","options":["The dogs bowl","The dog's bowl","The dogs' bowl","The dog' bowl"],"answer":1,"explain":"One dog owning the bowl: add 's."},
  {"type":"mcq","prompt":"Which shows correct possessive punctuation for several students?","options":["The student's books","The students's books","The students books","The students' books"],"answer":3,"explain":"A plural noun already ending in s adds only an apostrophe."},
  {"type":"mcq","prompt":"Which is correct?","options":["There isn't much furnitures in the flat.","There isn't much furniture in the flat.","There isn't many furniture in the flat.","There aren't much furniture in the flat."],"answer":1,"explain":"Furniture is uncountable: much (not many), no plural -s, and singular verb agreement (isn't)."},
  {"type":"type","prompt":"Give the plural form of 'box'.","accepted":["boxes"],"explain":"Nouns ending in x add -es."},
  {"type":"mcq","prompt":"Which sentence correctly distinguishes common and proper nouns?","options":["The Doctor works at a Hospital.","The doctor works at a hospital.","The doctor works at a Hospital.","the Doctor works at the hospital."],"answer":1,"explain":"Doctor and hospital are common nouns here (general roles/places), so neither is capitalised."},
  {"type":"mcq","prompt":"Choose the correctly punctuated sentence about a company's headquarters.","options":["The companys headquarters is in Tokyo.","The company's headquarters is in Tokyo.","The companies headquarters is in Tokyo.","The company' headquarters is in Tokyo."],"answer":1,"explain":"One company owning its headquarters: add 's."},
  {"type":"type","prompt":"Give the plural form of 'city'.","accepted":["cities"],"explain":"A consonant before y changes to -ies in the plural."},
],

pronouns: [
  {"type":"mcq","prompt":"Which sentence uses subject pronouns correctly?","options":["Me and him went to the shop.","Him and me went to the shop.","He and I went to the shop.","Me and he went to the shop."],"answer":2,"explain":"Both pronouns are the subject of 'went', so both need the subject form: he and I."},
  {"type":"mcq","prompt":"Which sentence uses the correct pronoun after a preposition?","options":["This is a secret between you and I.","This is a secret between you and me.","This is a secret between I and you.","This is a secret between you and myself."],"answer":1,"explain":"Between is a preposition and always takes the object form: me."},
  {"type":"mcq","prompt":"Which is correct?","options":["Is this bag your's?","Is this bag yours?","Is this bag yours'?","Is this bag you's?"],"answer":1,"explain":"Yours is a possessive pronoun and never takes an apostrophe."},
  {"type":"mcq","prompt":"Choose the sentence with the correct word.","options":["The cat licked it's paw.","The cat licked its paw.","The cat licked its' paw.","The cat licked it's' paw."],"answer":1,"explain":"Its (no apostrophe) is possessive; it's means 'it is'."},
  {"type":"mcq","prompt":"Which sentence avoids overusing a reflexive pronoun?","options":["Please send it to John or myself.","Please send it to John or me.","Please send it to John or I.","Please send it to John or mine."],"answer":1,"explain":"There's no reflexive relationship here, so the plain object pronoun me is correct."},
  {"type":"mcq","prompt":"Which sentence uses a reflexive pronoun correctly?","options":["She taught herself to code.","She taught her to code.","She taught hers to code.","She taught she to code."],"answer":0,"explain":"The subject (she) and the object are the same person, so the reflexive herself is correct."},
  {"type":"type","prompt":"Complete: 'This decision is entirely ___ to make.' (possessive pronoun for 'you')","accepted":["yours"],"explain":"A possessive pronoun stands alone at the end of the clause: yours."},
  {"type":"mcq","prompt":"Which sentence uses the correct contraction of they are?","options":["Their going on holiday next week.","There going on holiday next week.","They're going on holiday next week.","Ther're going on holiday next week."],"answer":2,"explain":"They're is the contraction of 'they are'."},
  {"type":"mcq","prompt":"Which correctly distinguishes a possessive adjective from a possessive pronoun?","options":["Is this her book? Yes, it's her's.","Is this her book? Yes, it's hers.","Is this hers book? Yes, it's her's.","Is this hers book? Yes, it's hers."],"answer":1,"explain":"'Her book' uses the possessive adjective (before a noun); 'it's hers' uses the possessive pronoun (stands alone, no apostrophe)."},
  {"type":"type","prompt":"Which pronoun completes: 'Nobody answered when I called ___.' (object form of 'he')","accepted":["him"],"explain":"After a verb, the object pronoun (him) is needed."},
  {"type":"mcq","prompt":"Choose the sentence where subject and object of the verb are the same person.","options":["She blamed him for the mistake.","She blamed herself for the mistake.","She blamed her for the mistake.","She blamed hers for the mistake."],"answer":1,"explain":"Herself is correct because the subject (she) and the object are the same person."},
],

verbs: [
  {"type":"mcq","prompt":"Which sentence uses a linking verb correctly?","options":["The soup tastes well.","The soup tastes good.","The soup tastes goodly.","The soup taste good."],"answer":1,"explain":"Taste is a linking verb here, so it's followed by the adjective good, not an adverb."},
  {"type":"mcq","prompt":"Which sentence uses an action verb correctly?","options":["She sang beautiful.","She sang beautifully.","She sang beauty.","She sang beautify."],"answer":1,"explain":"Sang is an action verb, so it needs the adverb beautifully to describe how she sang."},
  {"type":"type","prompt":"Give the past simple form of the irregular verb 'go'.","accepted":["went"],"explain":"Go is irregular: go, went, gone."},
  {"type":"type","prompt":"Give the past participle of the irregular verb 'write'.","accepted":["written"],"explain":"Write is irregular: write, wrote, written."},
  {"type":"mcq","prompt":"Which sentence correctly uses the intransitive verb lie?","options":["I'm going to lay down for an hour.","I'm going to lie down for an hour.","I'm going to lied down for an hour.","I'm going to laid down for an hour."],"answer":1,"explain":"Lie (to recline) is intransitive and takes no object — the correct base form here is lie."},
  {"type":"mcq","prompt":"Which sentence correctly uses the transitive verb lay?","options":["Please lie the book on the table.","Please lay the book on the table.","Please lain the book on the table.","Please lied the book on the table."],"answer":1,"explain":"Lay is transitive and takes an object (the book) — lay is correct here, not lie."},
  {"type":"mcq","prompt":"Which verb is transitive in this sentence: 'I borrowed a pen from her.'?","options":["borrowed","from","her","none of these"],"answer":0,"explain":"Borrowed is transitive — it requires a direct object (a pen) to complete its meaning."},
  {"type":"type","prompt":"Give the past simple form of the irregular verb 'see'.","accepted":["saw"],"explain":"See is irregular: see, saw, seen."},
  {"type":"mcq","prompt":"Which sentence uses the correct irregular past form of go?","options":["She goed to the market.","She go to the market.","She went to the market.","She gone to the market."],"answer":2,"explain":"Go's past simple is the irregular form went, not 'goed'."},
  {"type":"mcq","prompt":"Which sentence correctly uses a linking verb + adjective?","options":["He looked angrily at the report.","He looked angry at the report.","He looks angrily.","He look angry."],"answer":1,"explain":"Looked here is a linking verb describing his state, so it takes the adjective angry, not the adverb angrily (which would describe how he performed the action of looking, e.g. glancing sharply)."},
  {"type":"type","prompt":"Give the past participle of the irregular verb 'go'.","accepted":["gone"],"explain":"Go is irregular: go, went, gone."},
],

"adjectives-adverbs": [
  {"type":"mcq","prompt":"Which sentence correctly uses an adjective before a noun?","options":["He is a careful driver.","He is a carefully driver.","He drives careful.","He is a care driver."],"answer":0,"explain":"Careful is an adjective describing the noun driver."},
  {"type":"mcq","prompt":"Which sentence correctly uses an adverb to describe a verb?","options":["He drives careful.","He drives carefully.","He drives care.","He is drives carefully."],"answer":1,"explain":"Carefully is an adverb describing how he drives (the verb)."},
  {"type":"type","prompt":"Give the comparative form of 'busy'.","accepted":["busier"],"explain":"A two-syllable adjective ending in -y changes y to i and adds -er: busier."},
  {"type":"type","prompt":"Give the superlative form of 'good'.","accepted":["best","the best"],"explain":"Good has an irregular superlative: best."},
  {"type":"mcq","prompt":"Which sentence correctly forms the superlative of a longer adjective?","options":["That was the most interesting lecture.","That was the interestingest lecture.","That was the more interesting lecture.","That was the most interestingest lecture."],"answer":0,"explain":"Longer adjectives like interesting use 'most', not an -est ending."},
  {"type":"mcq","prompt":"Which sentence avoids a doubled comparative?","options":["This is the most easiest way.","This is the easiest way.","This is the most easy way.","This is easier way."],"answer":1,"explain":"Never combine 'most' with an -est ending — choose one form only."},
  {"type":"mcq","prompt":"Choose the sentence with correct adjective order.","options":["A wooden old small lovely table.","A lovely small old wooden table.","A small lovely wooden old table.","An old wooden lovely small table."],"answer":1,"explain":"The conventional order is opinion, size, age, shape, colour, origin, material: lovely (opinion), small (size), old (age), wooden (material)."},
  {"type":"mcq","prompt":"Which sentence correctly uses well instead of good?","options":["He did good on the test.","He did well on the test.","He did goodly on the test.","He did being good on the test."],"answer":1,"explain":"Well is the adverb needed to describe how he did; good is an adjective and can't modify 'did' here."},
  {"type":"type","prompt":"Give the comparative form of 'far'.","accepted":["further","farther"],"explain":"Far has an irregular comparative: further (or farther)."},
  {"type":"mcq","prompt":"Which sentence is correct?","options":["She sings beautiful.","She sings beautifully.","She sings beauty.","She sing beautifully."],"answer":1,"explain":"Sings is an action verb, so it needs the adverb beautifully."},
],

"prepositions-conjunctions": [
  {"type":"mcq","prompt":"Choose the correct preposition: 'The meeting is ___ Monday morning.'","options":["in","on","at","by"],"answer":1,"explain":"Days of the week take on."},
  {"type":"mcq","prompt":"Choose the correct preposition: 'I was born ___ 1998.'","options":["on","at","in","by"],"answer":2,"explain":"Years take in."},
  {"type":"mcq","prompt":"Choose the correct preposition: 'She's very good ___ languages.'","options":["in","at","on","for"],"answer":1,"explain":"The fixed pairing is good at."},
  {"type":"mcq","prompt":"Choose the correct preposition: 'He's interested ___ history.'","options":["on","for","in","at"],"answer":2,"explain":"The fixed pairing is interested in."},
  {"type":"mcq","prompt":"Which conjunction correctly joins two equal independent clauses?","options":["She was tired, because she finished the report.","She was tired, but she finished the report.","She was tired, if she finished the report.","She was tired, that she finished the report."],"answer":1,"explain":"But is a coordinating conjunction joining two grammatically equal, independent clauses."},
  {"type":"mcq","prompt":"Which is a subordinating conjunction?","options":["and","but","although","or"],"answer":2,"explain":"Although introduces a dependent clause; and, but, or are coordinating conjunctions."},
  {"type":"mcq","prompt":"Choose the sentence with parallel grammar after 'both...and'.","options":["She is both talented and hardworking.","She is both talented and works hard.","She both is talented and hardworking.","She is both talent and hardworking."],"answer":0,"explain":"Both sides of the pair should match grammatically — here, two adjectives: talented and hardworking."},
  {"type":"mcq","prompt":"Which sentence uses the correct fixed preposition after good?","options":["I'm good in maths.","I'm good at maths.","I'm good on maths.","I'm good for maths."],"answer":1,"explain":"The fixed pairing is good at, not good in."},
  {"type":"mcq","prompt":"Which sentence correctly uses despite?","options":["Despite of the rain, we went out.","Despite the rain, we went out.","Despite from the rain, we went out.","Despite about the rain, we went out."],"answer":1,"explain":"Despite is never followed by 'of' — use despite alone."},
  {"type":"type","prompt":"Complete with the correct preposition: 'The train leaves ___ platform 4.' (departure point)","accepted":["from"],"explain":"A departure point uses from."},
],

"articles-determiners": [
  {"type":"mcq","prompt":"Choose the correct article: 'She is ___ university professor.'","options":["a","an","the","(no article)"],"answer":0,"explain":"University starts with a consonant sound (/j/), so it takes a, not an."},
  {"type":"mcq","prompt":"Choose the correct article: 'I bought ___ umbrella yesterday.'","options":["a","an","the","(no article)"],"answer":1,"explain":"Umbrella starts with a vowel sound, so it takes an."},
  {"type":"mcq","prompt":"Which sentence correctly omits the article for a general concept?","options":["I love the nature.","I love nature.","I love a nature.","I love an nature."],"answer":1,"explain":"A general, uncountable concept like nature takes no article when speaking generally."},
  {"type":"mcq","prompt":"Which sentence uses any correctly in a plain question?","options":["Do you have some questions?","Do you have any questions?","Do you have a questions?","Do you have the questions?"],"answer":1,"explain":"A plain, neutral question normally takes any, not some."},
  {"type":"mcq","prompt":"Which sentence correctly uses the for a unique thing?","options":["The sun rises in the east.","A sun rises in an east.","Sun rises in east.","The sun rises in an east."],"answer":0,"explain":"The sun and the east are unique things both speaker and listener already know — both take the."},
  {"type":"mcq","prompt":"Which sentence uses some correctly in an offer?","options":["Would you like some tea?","Would you like any tea?","Would you like a tea?","Would you like the tea?"],"answer":0,"explain":"An offer phrased as a question typically uses some, not any."},
  {"type":"mcq","prompt":"Choose the correct sentence about a general statement.","options":["The children need affection.","Children need affection.","A children need affection.","Some children need affection to grow well, in general."],"answer":1,"explain":"A general statement about children as a whole takes no article."},
  {"type":"type","prompt":"Complete: 'I saw ___ elephant at the zoo.' (a or an)","accepted":["an"],"explain":"Elephant starts with a vowel sound, so it takes an."},
],

"sentence-patterns": [
  {"type":"mcq","prompt":"Identify the subject: 'The old bridge finally collapsed.'","options":["finally collapsed","The old bridge","collapsed","old"],"answer":1,"explain":"The old bridge is who/what the sentence is about; the rest is the predicate."},
  {"type":"mcq","prompt":"Which sentence follows the Subject-Verb-Object pattern?","options":["Birds fly.","She read the book.","He is a doctor.","She seems tired."],"answer":1,"explain":"She (S) read (V) the book (O) — a direct object receiving the action."},
  {"type":"mcq","prompt":"Which sentence follows the Subject-Verb-Complement pattern?","options":["She gave him a gift.","They elected her president.","He is a doctor.","Birds fly."],"answer":2,"explain":"Is links the subject (He) to a complement (a doctor) that renames him — no object is acted upon."},
  {"type":"mcq","prompt":"In 'She gave him a gift,' what is 'him'?","options":["direct object","indirect object","subject complement","subject"],"answer":1,"explain":"Him is the indirect object — the receiver of the direct object, 'a gift'."},
  {"type":"mcq","prompt":"Which of these is a complete sentence, not a fragment?","options":["Yesterday at the market with my sister.","Walking down the street in the rain.","I went to the market yesterday.","Because it was raining heavily."],"answer":2,"explain":"Only this option has both a subject (I) and a full verb (went) forming a complete thought."},
  {"type":"mcq","prompt":"Which sentence uses the correct pattern: gave the employee a bonus, or gave a bonus to employee?","options":["The manager gave a bonus to employee.","The manager gave the employee a bonus.","The manager gave to employee a bonus.","The manager gave employee the a bonus."],"answer":1,"explain":"A specific employee needs an article (the), and this pattern places the indirect object before the direct object without 'to'."},
],

"phrases-clauses": [
  {"type":"mcq","prompt":"Which is an independent clause?","options":["Because the rain stopped","Walking down the street","The rain stopped","In the middle of the night"],"answer":2,"explain":"The rain stopped has a subject and verb and expresses a complete thought — it can stand alone."},
  {"type":"mcq","prompt":"Which is a dependent clause?","options":["The rain stopped.","Because the rain stopped","In the middle of the night","Walking down the street"],"answer":1,"explain":"It has a subject and verb (the rain stopped) but 'because' makes it incomplete on its own."},
  {"type":"mcq","prompt":"Which of these is a phrase, not a clause?","options":["The rain stopped","Because the rain stopped","In the middle of the night","Although she was tired"],"answer":2,"explain":"In the middle of the night has no subject-verb pair, so it's a phrase, not a clause."},
  {"type":"mcq","prompt":"Choose the correctly punctuated sentence.","options":["Because I was late. I missed the bus.","Because I was late, I missed the bus.","Because, I was late, I missed the bus.","Because I was late I. missed the bus."],"answer":1,"explain":"The dependent clause 'because I was late' needs a comma, then to join directly to the independent clause — it can't be its own sentence."},
  {"type":"mcq","prompt":"Which sentence combines a dependent and an independent clause correctly?","options":["Although she was tired she finished the report.","Although she was tired, she finished the report.","Although, she was tired, she finished the report.","Although she was tired. She finished the report."],"answer":1,"explain":"A comma follows the introductory dependent clause before the independent clause begins."},
],

"sentence-types": [
  {"type":"mcq","prompt":"What type of sentence is 'Close the door.'?","options":["Declarative","Interrogative","Imperative","Exclamatory"],"answer":2,"explain":"An imperative sentence gives a command, with an implied subject 'you'."},
  {"type":"mcq","prompt":"What type of sentence is 'What a mess!'?","options":["Declarative","Interrogative","Imperative","Exclamatory"],"answer":3,"explain":"An exclamatory sentence expresses strong feeling."},
  {"type":"mcq","prompt":"Which sentence is compound?","options":["She studied hard, and she passed.","Although it rained, we went out.","She studied hard to pass.","Studying hard, she passed."],"answer":0,"explain":"Two independent clauses joined by a comma + coordinating conjunction (and) make a compound sentence."},
  {"type":"mcq","prompt":"Which sentence is complex?","options":["She studied hard, and she passed.","Although it was raining, we went for a walk.","She studied hard and passed.","It was raining. We went for a walk."],"answer":1,"explain":"One dependent clause (although it was raining) plus one independent clause makes a complex sentence."},
  {"type":"mcq","prompt":"Identify the error: 'I went to the store, I bought some milk.'","options":["Fragment","Comma splice","Dangling modifier","Subject-verb disagreement"],"answer":1,"explain":"Two independent clauses are joined by only a comma — a comma splice."},
  {"type":"type","prompt":"Fix this comma splice: 'The concert was cancelled, it kept raining.' Add ONE word after the comma to fix it.","accepted":["and","because"],"explain":"Adding a coordinating conjunction like 'and' (or 'because') after the comma fixes the splice."},
  {"type":"mcq","prompt":"Identify the error: 'Running through the park every morning.'","options":["Comma splice","Fragment","Misplaced modifier","Run-on"],"answer":1,"explain":"This phrase has no subject and finite verb of its own — it's a fragment, not a full sentence."},
  {"type":"mcq","prompt":"Which correctly fixes a run-on with a semicolon?","options":["The concert was cancelled; it kept raining all evening.","The concert was cancelled, it kept raining all evening.","The concert was cancelled; and it kept raining.","The concert; was cancelled it kept raining."],"answer":0,"explain":"A semicolon alone can join two closely related independent clauses."},
],

"present-past": [
  {"type":"mcq","prompt":"Choose the correct sentence for a routine.","options":["She go to the gym every morning.","She goes to the gym every morning.","She going to the gym every morning.","She is go to the gym every morning."],"answer":1,"explain":"Third-person singular subjects need -s in the present simple: goes."},
  {"type":"mcq","prompt":"Choose the correct sentence for something happening right now.","options":["She studies for her exam right now.","She's studying for her exam right now.","She studied for her exam right now.","She study for her exam right now."],"answer":1,"explain":"'Right now' signals an action in progress: present continuous."},
  {"type":"mcq","prompt":"Which sentence correctly avoids the continuous form of a state verb?","options":["I am knowing the answer.","I know the answer.","I am know the answer.","I knowing the answer."],"answer":1,"explain":"Know is a state verb and isn't used in the continuous form."},
  {"type":"mcq","prompt":"Choose the correct sentence for a fixed future arrangement.","options":["We meet the Johnsons on Saturday, it's already set.","We're meeting the Johnsons on Saturday.","We meeting the Johnsons on Saturday.","We will meeting the Johnsons on Saturday."],"answer":1,"explain":"The present continuous commonly expresses a fixed future arrangement."},
  {"type":"mcq","prompt":"Choose the correct sentence for a finished past event.","options":["She has graduated in 2018.","She graduated in 2018.","She was graduating in 2018.","She graduate in 2018."],"answer":1,"explain":"A specific past time (2018) needs the past simple, not the present perfect."},
  {"type":"mcq","prompt":"Choose the correct sentence: an action interrupted another.","options":["I cooked dinner when the phone was ringing.","I was cooking dinner when the phone rang.","I was cooking dinner when the phone was ringing.","I cook dinner when the phone rang."],"answer":1,"explain":"The longer background action (cooking) is past continuous; the shorter interrupting action (rang) is past simple."},
  {"type":"type","prompt":"Give the correct verb form: 'I ___ (see) that film last week.' (past simple)","accepted":["saw"],"explain":"The past simple of see is saw."},
  {"type":"mcq","prompt":"Which sentence correctly uses the present simple for a routine?","options":["The store open at nine every day.","The store opens at nine every day.","The store opening at nine every day.","The store is open at nine every day, usually."],"answer":1,"explain":"A scheduled fact/routine uses the present simple, with -s for the third-person singular subject 'store'."},
],

"perfect-continuous": [
  {"type":"mcq","prompt":"Choose the correct sentence for an experience with no specific time given.","options":["She visited Japan twice.","She has visited Japan twice.","She was visiting Japan twice.","She visits Japan twice."],"answer":1,"explain":"Experience up to now with no specific time given uses the present perfect."},
  {"type":"mcq","prompt":"Choose the correct sentence with a specific past time.","options":["She has visited Japan in 2019.","She visited Japan in 2019.","She was visited Japan in 2019.","She has visit Japan in 2019."],"answer":1,"explain":"A specific time (2019) requires the past simple, not the present perfect."},
  {"type":"mcq","prompt":"Choose the correct word: 'They've lived here ___ six years.'","options":["since","for","from","during"],"answer":1,"explain":"For measures a length of time."},
  {"type":"mcq","prompt":"Choose the correct word: 'They've lived here ___ 2020.'","options":["for","during","since","from"],"answer":2,"explain":"Since marks a starting point in time."},
  {"type":"mcq","prompt":"Choose the sentence showing an earlier of two past events.","options":["When we arrived, the film already started.","When we arrived, the film had already started.","When we arrived, the film has already started.","When we arrived, the film already starts."],"answer":1,"explain":"The past perfect (had started) marks the event that happened before another past event (arrived)."},
  {"type":"mcq","prompt":"Which sentence correctly uses the past simple with a specific time marker?","options":["I have seen that film yesterday.","I saw that film yesterday.","I have see that film yesterday.","I was seeing that film yesterday."],"answer":1,"explain":"Yesterday is a specific past time marker, which requires the past simple, not the present perfect."},
  {"type":"mcq","prompt":"Which sentence correctly uses since with the present perfect continuous?","options":["She is living here since 2015.","She has been living here since 2015.","She lives here since 2015.","She was living here since 2015."],"answer":1,"explain":"Since requires the present perfect (continuous), not the present continuous."},
],

"future-forms": [
  {"type":"mcq","prompt":"Choose the correct sentence for a spontaneous decision.","options":["The phone's ringing — I'm going to get it.","The phone's ringing — I'll get it.","The phone's ringing — I get it.","The phone's ringing — I'm getting it."],"answer":1,"explain":"A decision made at the moment of speaking uses will."},
  {"type":"mcq","prompt":"Choose the correct sentence for a plan already decided.","options":["I've decided — I'll apply for the job.","I've decided — I'm going to apply for the job.","I've decided — I apply for the job.","I've decided — I applied for the job."],"answer":1,"explain":"A plan formed before the moment of speaking uses going to."},
  {"type":"mcq","prompt":"Choose the correct sentence for a prediction based on visible evidence.","options":["Look at those clouds — it will rain.","Look at those clouds — it's going to rain.","Look at those clouds — it rains.","Look at those clouds — it's raining."],"answer":1,"explain":"Going to is used for predictions based on something visible right now."},
  {"type":"mcq","prompt":"Choose the correct sentence for something complete before a future deadline.","options":["By next year, she will graduate.","By next year, she will have graduated.","By next year, she is graduating.","By next year, she graduates."],"answer":1,"explain":"The future perfect (will have + past participle) shows something complete before a stated future point."},
  {"type":"mcq","prompt":"Choose the correct sentence for an action in progress at a specific future moment.","options":["This time tomorrow, I'll fly home.","This time tomorrow, I'll be flying home.","This time tomorrow, I fly home.","This time tomorrow, I flew home."],"answer":1,"explain":"The future continuous (will be + -ing) shows an action in progress at a specific future time."},
  {"type":"mcq","prompt":"Which sentence avoids incorrectly combining will and going to?","options":["I think it will going to rain.","I think it's going to rain.","I think it will to rain.","I think it going to rain."],"answer":1,"explain":"Will and going to are separate future forms and shouldn't be combined."},
],

"active-passive": [
  {"type":"mcq","prompt":"Identify the passive sentence.","options":["The chef prepared the meal.","The meal was prepared by the chef.","The chef is preparing the meal.","The chef will prepare the meal."],"answer":1,"explain":"The subject (the meal) receives the action, and the performer is introduced with 'by' — this is passive voice."},
  {"type":"mcq","prompt":"Choose the correct present simple passive form.","options":["The report reviews every month.","The report is reviewed every month.","The report is reviewing every month.","The report reviewed every month."],"answer":1,"explain":"Present simple passive: is + past participle."},
  {"type":"mcq","prompt":"Choose the correct past simple passive form.","options":["The bridge built in 1932.","The bridge was built in 1932.","The bridge is built in 1932.","The bridge was building in 1932."],"answer":1,"explain":"Past simple passive: was/were + past participle."},
  {"type":"mcq","prompt":"Fix the error: 'The vase was broke by the cat.'","options":["The vase was breaking by the cat.","The vase was broken by the cat.","The vase broke by the cat.","The vase is broke by the cat."],"answer":1,"explain":"The passive needs the past participle (broken), not the past simple form (broke)."},
  {"type":"mcq","prompt":"Fix the agreement error: 'Mistakes was made during the project.'","options":["Mistakes is made during the project.","Mistakes were made during the project.","Mistake was made during the project.","Mistakes was making during the project."],"answer":1,"explain":"Mistakes is plural, so the passive auxiliary must also be plural: were."},
  {"type":"mcq","prompt":"Which situation best fits using the passive voice?","options":["You know exactly who did something and want to highlight them.","The performer of the action is unknown or unimportant.","You're writing a very casual, conversational text message.","You want maximum clarity about who is responsible."],"answer":1,"explain":"The passive is most useful when the doer is unknown, unimportant, or obvious from context."},
],

"reported-speech": [
  {"type":"type","prompt":"Report this: 'I am tired,' she said. → She said she ___ tired. (verb only)","accepted":["was"],"explain":"Present simple (am) backshifts to past simple (was) in reported speech."},
  {"type":"type","prompt":"Report this: 'I have finished,' he said. → He said he ___ finished. (auxiliary only)","accepted":["had"],"explain":"Present perfect (have) backshifts to past perfect (had) in reported speech."},
  {"type":"type","prompt":"Report this: 'I will call you,' she said. → She said she ___ call me. (modal only)","accepted":["would"],"explain":"Will backshifts to would in reported speech."},
  {"type":"mcq","prompt":"Choose the correctly reported question: 'Are you coming?' she asked.","options":["She asked was I coming?","She asked if I was coming.","She asked if I am coming.","She asked am I coming."],"answer":1,"explain":"Reported yes/no questions use if, normal statement word order, and backshift the tense."},
  {"type":"mcq","prompt":"Choose the correctly reported question: 'Where do you live?' he asked.","options":["He asked where did I live.","He asked where I lived.","He asked where do I live.","He asked where I live?"],"answer":1,"explain":"Reported wh-questions keep the question word but use normal statement word order."},
  {"type":"mcq","prompt":"Choose the correctly reported command: 'Wait here,' he said.","options":["He told me wait there.","He told me to wait there.","He told me that wait there.","He said me to wait there."],"answer":1,"explain":"Commands are reported as told + object + to-infinitive."},
  {"type":"mcq","prompt":"Which sentence correctly distinguishes tell from say?","options":["He asked where did I live.","She told to me to wait.","She told me to wait.","He said me where I lived."],"answer":2,"explain":"Tell takes a direct object without 'to' (told me), unlike say (said to me)."},
],

modals: [
  {"type":"mcq","prompt":"Which sentence correctly follows a modal with the base verb?","options":["She can to swim very well.","She can swim very well.","She cans swim very well.","She can swimming very well."],"answer":1,"explain":"Modals are followed directly by the base verb — never add 'to' after can."},
  {"type":"mcq","prompt":"Choose the correct sentence for a prohibition.","options":["You mustn't smoke in here.","You don't have to smoke in here.","You not must smoke in here.","You haven't to smoke in here."],"answer":0,"explain":"Mustn't expresses that something is prohibited."},
  {"type":"mcq","prompt":"Choose the correct sentence for something optional, not prohibited.","options":["You mustn't come if you're busy.","You don't have to come if you're busy.","You shouldn't come if you're busy.","You can't come if you're busy."],"answer":1,"explain":"Don't have to means it's optional; mustn't would wrongly suggest it's prohibited."},
  {"type":"mcq","prompt":"Choose the sentence expressing a confident positive deduction.","options":["The lights are off — they might be out.","The lights are off — they must be out.","The lights are off — they can be out.","The lights are off — they should be out."],"answer":1,"explain":"Must expresses a confident positive conclusion."},
  {"type":"mcq","prompt":"Choose the sentence expressing a confident negative deduction.","options":["She mustn't have forgotten — she never forgets.","She can't have forgotten — she never forgets.","She shouldn't have forgotten — she never forgets.","She won't have forgotten — she never forgets."],"answer":1,"explain":"Can't have expresses a confident negative deduction about the past."},
  {"type":"mcq","prompt":"Choose the correct sentence expressing regret about the past.","options":["You should have called me first.","You should call me first.","You should have call me first.","You should to have called me first."],"answer":0,"explain":"Should have + past participle expresses regret about something that didn't happen."},
  {"type":"mcq","prompt":"Fix the error: 'He should have went earlier.'","options":["He should have go earlier.","He should have gone earlier.","He should has gone earlier.","He should have going earlier."],"answer":1,"explain":"Should have takes the past participle (gone), not the past simple (went)."},
],

conditionals: [
  {"type":"mcq","prompt":"Identify the conditional type: 'If you heat ice, it melts.'","options":["Zero","First","Second","Third"],"answer":0,"explain":"A zero conditional states a general, always-true result."},
  {"type":"mcq","prompt":"Identify the conditional type: 'If it rains, we'll stay home.'","options":["Zero","First","Second","Third"],"answer":1,"explain":"A first conditional describes a real, likely future possibility."},
  {"type":"mcq","prompt":"Identify the conditional type: 'If I won the lottery, I would travel the world.'","options":["Zero","First","Second","Third"],"answer":2,"explain":"A second conditional describes a hypothetical or unlikely present/future situation."},
  {"type":"mcq","prompt":"Identify the conditional type: 'If she had studied harder, she would have passed.'","options":["First","Second","Third","Zero"],"answer":2,"explain":"A third conditional describes an imaginary alternative to something already in the past."},
  {"type":"mcq","prompt":"Fix the error: 'If I would have known, I would have called.'","options":["If I had known, I would have called.","If I would know, I would have called.","If I have known, I would have called.","If I knew, I would have called."],"answer":0,"explain":"The if-clause of a third conditional uses the past perfect (had known), not would have."},
  {"type":"mcq","prompt":"Choose the correct subjunctive sentence.","options":["I wish I am taller.","I wish I were taller.","I wish I was taller in a normal sense.","I wish I be taller."],"answer":1,"explain":"Wish about a present state uses were for every subject — this is the subjunctive."},
  {"type":"mcq","prompt":"Choose the correct formal sentence.","options":["If I was you, I'd apologise.","If I were you, I'd apologise.","If I am you, I'd apologise.","If I would be you, I'd apologise."],"answer":1,"explain":"In this fixed, formal expression, were is used for every subject, including I."},
  {"type":"mcq","prompt":"Choose the sentence expressing regret about the past with 'wish'.","options":["I wish I study harder.","I wish I studied harder.","I wish I had studied harder.","I wish I have studied harder."],"answer":2,"explain":"Wish + past perfect expresses regret about the past."},
],

agreement: [
  {"type":"mcq","prompt":"Which sentence correctly agrees with its true subject, not a nearby noun?","options":["The list of items on the shelf are long.","The list of items on the shelf is long.","The list of items on the shelf were long.","The list of items on the shelf be long."],"answer":1,"explain":"The true subject is 'list' (singular), not 'items' — the verb agrees with list."},
  {"type":"mcq","prompt":"Which sentence correctly matches everyone with a singular verb?","options":["Everyone have their own opinion.","Everyone has their own opinion.","Everyone having their own opinion.","Everyone are having their own opinion."],"answer":1,"explain":"Everyone is grammatically singular and takes has, not have."},
  {"type":"mcq","prompt":"Choose the correct sentence in standard American style.","options":["The team are playing well this season.","The team is playing well this season.","The team be playing well this season.","The team were play well this season."],"answer":1,"explain":"In standard American style, collective nouns like team take a singular verb as one unit."},
  {"type":"mcq","prompt":"Which sentence correctly treats \"one of\" as a singular subject?","options":["One of my colleagues are from Brazil.","One of my colleagues is from Brazil.","One of my colleagues be from Brazil.","One of my colleagues were from Brazil."],"answer":1,"explain":"The true subject is 'one', which is singular, not 'colleagues'."},
  {"type":"mcq","prompt":"Which sentence correctly applies the neither...nor agreement rule?","options":["Neither the manager nor the employees were informed.","Neither the manager nor the employees was informed.","Neither the manager nor the employees is informed.","Neither the manager or the employees were informed."],"answer":0,"explain":"With neither...nor, the verb agrees with the nearer subject (employees, plural), so were is correct."},
  {"type":"mcq","prompt":"Which sentence correctly matches each with a singular verb?","options":["Each of the students have a locker.","Each of the students has a locker.","Each of the students having a locker.","Each of the students are have a locker."],"answer":1,"explain":"Each is singular, even before a plural noun (students), so it takes has."},
  {"type":"mcq","prompt":"Choose the sentence where the inserted phrase doesn't change the verb's agreement.","options":["The manager, along with her team, are attending the conference.","The manager, along with her team, is attending the conference.","The manager, along with her team, be attending the conference.","The manager, along with her team, were attending the conference."],"answer":1,"explain":"'Along with her team' doesn't change the subject — manager is still singular, so is is correct."},
],

modifiers: [
  {"type":"mcq","prompt":"Which sentence implies 'nobody else did'?","options":["She only ate a sandwich for lunch.","Only she ate a sandwich for lunch.","She ate only a sandwich for lunch.","She ate a sandwich only for lunch."],"answer":1,"explain":"Placing 'only' right before 'she' means nobody else ate a sandwich."},
  {"type":"mcq","prompt":"Identify the dangling modifier problem: 'Walking to the station, the rain started to fall.'","options":["This is correct as written.","It implies the rain was walking to the station.","It's a run-on sentence.","It's a comma splice."],"answer":1,"explain":"The opening phrase has no logical human subject to attach to — as written, it describes the rain walking."},
  {"type":"mcq","prompt":"Choose the corrected version.","options":["Walking to the station, the rain started to fall.","Walking to the station, I got caught in the rain.","Walking to the station the rain started falling.","The rain, walking to the station, started to fall."],"answer":1,"explain":"'I' is now the subject that logically follows and matches the opening phrase."},
  {"type":"mcq","prompt":"Choose the sentence with a defining (restrictive) relative clause.","options":["My car, which is quite old, still runs well.","The woman who called earlier left a message.","London, which I visited last year, was lovely.","My father, who lives nearby, visits often."],"answer":1,"explain":"This clause identifies exactly which woman is meant, with no commas — a defining clause."},
  {"type":"mcq","prompt":"Choose the correct relative pronoun for a non-defining clause about a thing.","options":["My car, that I bought last year, needs repairing.","My car, which I bought last year, needs repairing.","My car, who I bought last year, needs repairing.","My car, whom I bought last year, needs repairing."],"answer":1,"explain":"A non-defining clause (set off by commas) requires which for things, not that."},
  {"type":"mcq","prompt":"Choose the corrected version of: 'I almost drove my kids to school every day that year.'","options":["This is already correct.","I drove my kids to school almost every day that year.","I drove almost my kids to school every day that year.","Almost I drove my kids to school every day."],"answer":1,"explain":"As originally placed, almost wrongly suggests the driving nearly didn't happen; moving it fixes the meaning to describe frequency."},
],

punctuation: [
  {"type":"mcq","prompt":"Choose the correctly punctuated sentence.","options":["After the meeting we grabbed lunch.","After the meeting, we grabbed lunch.","After, the meeting we grabbed lunch.","After the meeting, we, grabbed lunch."],"answer":1,"explain":"A comma follows an introductory phrase."},
  {"type":"mcq","prompt":"Choose the correctly punctuated possessive.","options":["The dogs bowl is empty.","The dog's bowl is empty.","The dog bowl's is empty.","The dogs' bowl is empty (for one dog)."],"answer":1,"explain":"One dog owning the bowl: add 's."},
  {"type":"mcq","prompt":"Choose the correct fix for this comma splice: 'I have a lot of work to do, I can't come tonight.'","options":["I have a lot of work to do; I can't come tonight.","I have a lot of work to do, I can't, come tonight.","I have, a lot of work to do, I can't come tonight.","This is already correct."],"answer":0,"explain":"A semicolon can join two closely related independent clauses without a conjunction."},
  {"type":"mcq","prompt":"Choose the correctly punctuated sentence introducing a list.","options":["You'll need three things, a pen, paper, and time.","You'll need three things: a pen, paper, and time.","You'll need three things; a pen, paper, and time.","You'll need: three things a pen, paper, and time."],"answer":1,"explain":"A colon introduces a list after a complete clause."},
  {"type":"mcq","prompt":"Choose the correct fix for: 'There's only one thing I want, success.'","options":["There's only one thing I want; success.","There's only one thing I want: success.","There's only one thing I want, success!","This is already correct."],"answer":1,"explain":"A colon, not a comma, introduces this single-item explanation."},
  {"type":"mcq","prompt":"Choose the sentence with the full stop correctly placed relative to the quotation mark (American style).","options":["She said, \"I'll be there at noon\".","She said, \"I'll be there at noon.\"","She said \"I'll be there at noon.\"","She said, I'll be there at noon."],"answer":1,"explain":"In American style, the full stop sits inside the closing quotation mark, and a comma introduces the quote."},
  {"type":"mcq","prompt":"Which correctly uses an apostrophe for a contraction, not a plural?","options":["Apple's for sale.","Apples for sale.","It's a lovely day.","Its a lovely day."],"answer":2,"explain":"It's = it is, correctly using an apostrophe for a contraction, not a plural."},
],

"usage-style": [
  {"type":"mcq","prompt":"Choose the word that means 'a result' (noun).","options":["affect","effect","effected","affecting"],"answer":1,"explain":"Effect is usually the noun, meaning a result."},
  {"type":"mcq","prompt":"Choose the word that means 'to influence' (verb).","options":["effect","affect","effective","effects"],"answer":1,"explain":"Affect is usually the verb, meaning to influence."},
  {"type":"mcq","prompt":"Choose the correct sentence for a countable noun.","options":["There was less people than we expected.","There were fewer people than we expected.","There was fewer people than we expected.","There were less people than we expected."],"answer":1,"explain":"People is countable, so fewer (not less) is needed, and the plural verb were agrees with it."},
  {"type":"mcq","prompt":"Which sentence correctly distinguishes whose from whos apostrophe s?","options":["Who's coat is this?","Whose coat is this?","Who's coat this is?","Whose's coat is this?"],"answer":1,"explain":"Whose is possessive; who's means 'who is'."},
  {"type":"mcq","prompt":"Which sentence correctly distinguishes than from then?","options":["I'd rather walk then drive.","I'd rather walk than drive.","I'd rather walk them drive.","I'd rather walk, then, drive."],"answer":1,"explain":"Than is used for comparison; then relates to time or sequence."},
  {"type":"mcq","prompt":"Choose the sentence without a redundant phrase.","options":["It was a free gift.","It was a gift.","It was an advance warning.","It was a past history."],"answer":1,"explain":"Free gift is redundant — gifts are free by definition."},
  {"type":"mcq","prompt":"Choose the sentence with correct parallel structure.","options":["She likes hiking, to swim, and cycling.","She likes hiking, swimming, and cycling.","She likes to hike, swimming, and cycling.","She likes hike, swim, and cycling."],"answer":1,"explain":"All three items match grammatically as -ing forms: hiking, swimming, cycling."},
  {"type":"mcq","prompt":"Choose the more concise, less wordy sentence.","options":["Due to the fact that it rained, we stayed in.","Because it rained, we stayed in.","Owing to the fact of the rain, we stayed in.","In light of the fact that it rained, we stayed in."],"answer":1,"explain":"Because is far more concise than the wordy 'due to the fact that'."},
  {"type":"mcq","prompt":"Choose the sentence that keeps a parallel list of adjectives.","options":["The report was clear, concise, and it persuaded people.","The report was clear, concise, and persuasive.","The report was clear, concision, and persuasive.","The report was clearly, concise, and persuasive."],"answer":1,"explain":"All three items should be adjectives, matching clear and concise: persuasive."},
],

};
